name: Patterns to Code
description: Transforming Patterns to Code
meta_description: "Transforming Patterns to Code"

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://www.patternstocode.com'
google_analytics: 'UA-68647788-1'
disqus: true
disqus_shortname: 'patternstocode'

# Details for the RSS feed generator
url:            'http://www.patternstocode.com'
author:         'Chris Pilcher'
authorTwitter:  'nzchrisp'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
